# Package
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# Package information
[tool.poetry]
packages = [{ include = "aurum" }]
name = "aurum-hikari"
version = "0.1.1"
license = "MIT"
authors = ["stefanlight <64615032+stefanlight8@users.noreply.github.com>"]
description = "A flexible command & component handler"
keywords = [
    "discord",
    "hikari",
    "commands",
    "components",
    "command-handler",
    "component-handler",
]
classifiers = [
    "Development Status :: 1 - Planning",                           # TODO: Set `Development Status :: 3 - Alpha` later
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Communications :: Chat",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]
readme = "README.md"


[tool.poetry.urls]
repository = "https://github.com/ShinshiDevs/aurum-hikari"
documentation = "https://shinshidevs.github.io/aurum-hikari/docs/"
"Bug Tracker" = "https://github.com/ShinshiDevs/aurum-hikari/issues"
# TODO: Add discord later


# Package dependencies
[tool.poetry.dependencies]
python = ">=3.10,<3.13"
hikari = ">2.0.0.dev120"


# Developers stuff 
[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
ruff = "^0.4.3"

# Developers stuff: Ruff settings
[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.per-file-ignores] # borrowed from hikari-lightbulb
"__init__.py" = ["F401", "F403", "F405"]
