# DO NOT MANUALLY EDIT THIS FILE!
# This file was automatically generated by `nox -s generate_stubs`

from aurum.commands.decorators.sub_command import sub_command as sub_command

__all__ = ["sub_command"]
