name: docs

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  docs:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"
        - name: Poetry install
          run: pip install poetry
        - name: Install dependencies
          run: poetry install --group docs
        - name: Build documentation
          run: mkdocs build --strict

      